# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k79Wt_skDaRChdspr4VF1UctR3KVRhMA
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Load cleaned dataset
cleaned_data_path = "/content/cleaned_frailty_data.csv"
df = pd.read_csv(cleaned_data_path)

# Standardize column names
df.columns = df.columns.str.lower().str.strip()
print("Updated Column Names:", df.columns)

# Ensure results directory exists
os.makedirs("results", exist_ok=True)

# Compute and save summary statistics
summary_stats = df.describe()
summary_stats.to_csv("results/summary_statistics.txt")

# Compute and save correlation matrix
correlation_matrix = df.corr()
correlation_matrix.to_csv("results/correlation_matrix.txt")

print("✅ Data analysis completed. Results saved.")

# Ensure correct column name for plotting
if "grip strength" in df.columns:
    grip_strength_col = "grip strength"
elif "grip_strength" in df.columns:
    grip_strength_col = "grip_strength"
else:
    raise KeyError("Column 'Grip Strength' not found. Check CSV headers.")

# ✅ Bar Plot: Average Grip Strength by Frailty Status
plt.figure(figsize=(6, 4))
sns.barplot(x=df["frailty"], y=df[grip_strength_col], estimator=lambda x: x.mean(), ci=None)
plt.title("Average Grip Strength by Frailty Status")
plt.xlabel("Frailty (1 = Yes, 0 = No)")
plt.ylabel("Average Grip Strength (kg)")
plt.xticks(ticks=[0, 1], labels=["No Frailty", "Frailty"])
plt.grid()

# Save bar plot
bar_plot_path = "results/average_grip_strength_frailty.png"
plt.savefig(bar_plot_path)
plt.show()

print("✅ Bar plot saved in 'results/' directory.")