# -*- coding: utf-8 -*-
"""clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTVSagelPPxuqrIntB9j1p2MpTO82FA2
"""

import pandas as pd

# Load dataset (update file path accordingly)
file_path = "/content/frailty_data.csv"
df = pd.read_csv(file_path)

# Convert Frailty (Y/N) to binary (1 = Yes, 0 = No)
df["Frailty"] = df["Frailty"].map({"Y": 1, "N": 0})


# Save cleaned dataset
cleaned_file_path = "/content/cleaned_frailty_data.csv"
df.to_csv(cleaned_file_path, index=False)

print(" Data cleaning completed. Cleaned data saved at:", cleaned_file_path)
